version: "3.8"

services:
  # App Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sb_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - sb_network

  # Web Server
  nginx:
    image: nginx:alpine
    container_name: sb_nginx
    restart: unless-stopped
    ports:
      - "8080:80" # VPS akses port 8080, Nginx Proxy Manager arahkan ke sini
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sb_network
    depends_on:
      - app

  # Database
  db:
    image: mysql:8.0
    container_name: sb_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-sembakobayiponorogo}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password_vps_anda}
    volumes:
      - sb_db_data:/var/lib/mysql
    networks:
      - sb_network

  # Gowa (WhatsApp Automation)
  gowa:
    image: gowa/gowa:latest # Sesuaikan dengan image resmi gowa
    container_name: sb_gowa
    restart: always
    networks:
      - sb_network

networks:
  sb_network:
    driver: bridge

volumes:
  sb_db_data:
