services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt
    networks:
      - sb_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sb_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
      - /var/www/html/public/build/
    networks:
      - sb_network

  db:
    image: mysql:8.0
    container_name: sb_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-sembakobayiponorogo}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-191205}
    volumes:
      - sb_db_data:/var/lib/mysql
    networks:
      - sb_network

  gowa:
    image: aldinokemal2104/go-whatsapp-web-multidevice:latest
    container_name: sb_gowa
    restart: always
    expose:
      - 3000
    networks:
      - sb_network

networks:
  sb_network:
    driver: bridge

volumes:
  sb_db_data: