version: "3.8"

services:
  # App Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sb_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      # Kita tidak perlu menulis storage & bootstrap secara terpisah 
      # karena sudah tercakup di dalam folder "." (root) di atas.
    networks:
      - sb_network

  # Web Server
  nginx:
    image: nginx:alpine
    container_name: sb_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sb_network
    depends_on:
      - app

  # Database
  db:
    image: mysql:8.0
    container_name: sb_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-sembakobayiponorogo}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-191205}
    volumes:
      - sb_db_data:/var/lib/mysql
    networks:
      - sb_network

  # Gowa
  gowa:
    image: gowatech/gowa:latest
    container_name: sb_gowa
    restart: always
    networks:
      - sb_network

networks:
  sb_network:
    driver: bridge

volumes:
  sb_db_data: